system:
  runMode: local
  verbose: yes
  user: admin
  ifAdmin: yes
  force: yes

xcode:
  update: no

notify:
  title: A Title
  iconPath: "/Library/Application Support/JAMF/Jamf.app/Contents/Resources/AppIcon.icns"
  dialog: Reinstalling this app. This may take some time. Want to continue?
  timeout: 10
  allowCancel: yes
  display: yes

brew:
  install: no
  uninstall: no
  reset: no
  update: yes

package:
  install: no
  delete: no
  killProcess: thisapp
  reset: thisapp
  force: no

brass:
  update: no
  debug: yes

notify:
  title: Another Title
  iconPath: "/Library/Application Support/JAMF/Jamf.app/Contents/Resources/AppIcon.icns"
  dialog: App install complete.
  timeout: 10
  allowCancel: no
  display: yes
