verbose: level 2

system:
  branch: brass-testing
  runMode: system
  verbose: yes
  user: lcadmin
  ifAdmin: yes
  force: yes

package:
  manage: wget

system: 
  runMode: local
  verbose: yes
  user: lcadmin
  ifAdmin: no
  force: yes

package:
  manage: google-chrome
  manage: google-drive
  manage: slack
  manage: 1password
  manage: zoom
  option: atom
  option: microsoft-office
  option: tabby
  option: adobe-acrobat-reader 
